#!/bin/bash

SOLVER=$1
mkdir ~/git/icfpc2018/solutions/main/${SOLVER}
echo "Created ~/git/icfpc2018/solutions/main/${SOLVER}"

for sourcefile in /home/dreske/git/icfpc2018/task/reconstruct/*_src.mdl; do
	targetfile=${sourcefile/_src./_tgt.}
	[ -e "$sourcefile" ] || continue
	TARGET=`echo ${sourcefile} | sed "s/.*\///" | cut -d'_' -f 1`
	TARGET="/home/dreske/git/icfpc2018/solutions/main/${SOLVER}/${TARGET}.nbt"
	java -Xms2g -Xss500m -jar /home/dreske/git/icfpc2018/build/libs/icfpc2018-0.0.1.jar solve ${sourcefile} ${targetfile} ${TARGET} ${SOLVER}
	echo "Created ${TARGET}"
done
