#!/bin/bash

if [ ! -f link.txt ]; then
	echo "URL file link.txt not found!"
	exit 1
fi

if [ ! -f sha.txt ]; then
	echo "SHA file sha.txt not found!"
	exit 1
fi

if [ ! -f privateID ]; then
	echo "privateID file not found!"
	exit 1
fi

if [ ! -f file.txt ]; then
	echo "file.txt not found!"
	exit 1
fi

FILE=`cat file.txt`
URL=`cat link.txt`
SHA=`cat sha.txt`
KEY=`cat privateID`

echo "waiting for dropbox sync on ${FILE}"
STATUS=`dropbox filestatus ${FILE}`
while [ "${STATUS}" != "${FILE}: up to date" ]
do
	echo "status is ${STATUS} - waiting 5 seconds"
	sleep 5
	STATUS=`dropbox filestatus ${FILE}`	
done
echo "status is ${STATUS}"

echo "Submitting solutions via API..."

curl -L \
  --data-urlencode entry.1763695394=${KEY} \
  --data-urlencode entry.1501594990=${URL} \
  --data-urlencode entry.1453391049=${SHA} \
  https://docs.google.com/forms/u/2/d/e/1FAIpQLSd0RMj0IUNsoVmhlQotcDVMZakK921zShK8H42zQJiweRhb4g/formResponse


